LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE =
LOCAL_MODULE = mtk_agpsd
LOCAL_MODULE_CLASS = EXECUTABLES
LOCAL_MODULE_RELATIVE_PATH = $(TARGET_OUT_VENDOR_EXECUTABLES)
LOCAL_MODULE_SUFFIX =
LOCAL_MODULE_STEM =
LOCAL_MODULE_STEM_32 =
LOCAL_MODULE_STEM_64 =
LOCAL_SHARED_LIBRARIES = libcrypto libssl libicuuc libnetd_client libandroid_net libc++
LOCAL_MULTILIB = 32
LOCAL_SRC_FILES_32 = mtk_agpsd
#LOCAL_INIT_RC := mtk_agpsd.rc
include $(BUILD_PREBUILT)
